[OM-59626]: Send Approval to ServiceNOW and Receive Approval from ServiceNOW
Intent
======
Fix issues along the code path of sending approvals to ServiceNOW and and the path back receiving accepted approvals from ServiceNOW.

Problems and Solutions
======================

1. Add try catch around method used in ExecutorService to prevent it from swallowing threads that are never scheduled again:
```
java.lang.IllegalArgumentException: Operation class class com.vmturbo.topology.processor.operation.actionapproval.ActionApproval is not supported
	at com.vmturbo.topology.processor.api.server.TopologyProcessorNotificationSender.getOperationListener(TopologyProcessorNotificationSender.java:296)
	at com.vmturbo.topology.processor.api.server.TopologyProcessorNotificationSender.notifyOperationState(TopologyProcessorNotificationSender.java:264)
	at com.vmturbo.topology.processor.operation.OperationManager.operationStart(OperationManager.java:1137)
	at com.vmturbo.topology.processor.operation.OperationManager.approveActions(OperationManager.java:1320)
	at com.vmturbo.topology.processor.actions.ActionApprovalService.actionApprovalRequested(ActionApprovalService.java:128)
	at com.vmturbo.components.api.localbus.LocalBusTopic$TopicListener.run(LocalBusTopic.java:126)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

2. Add notification handlers to `TopologyProcessorNotificationSender` to fix this expection:
```
Exception in thread "result-handler" java.lang.IllegalArgumentException: Operation class class com.vmturbo.topology.processor.operation.actionapproval.ActionApproval is not supported
	at com.vmturbo.topology.processor.api.server.TopologyProcessorNotificationSender.getOperationListener(TopologyProcessorNotificationSender.java:296)
	at com.vmturbo.topology.processor.api.server.TopologyProcessorNotificationSender.notifyOperationState(TopologyProcessorNotificationSender.java:264)
	at com.vmturbo.topology.processor.operation.OperationManager.operationComplete(OperationManager.java:1160)
	at com.vmturbo.topology.processor.operation.OperationManager.access$200(OperationManager.java:116)
	at com.vmturbo.topology.processor.operation.OperationManager$InternalOperationCallback.lambda$onSuccess$0(OperationManager.java:1618)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

3. Add explanation to ExecuteActionRequest because ServiceNow requires an explanation.

4. Add includeAllActionsInTransition(true) to fix this exception:
```
com.google.protobuf.UninitializedMessageException: Message missing required fields: includeAllActionsInTransition
	at com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException(AbstractMessage.java:477)
	at com.vmturbo.platform.sdk.common.MediationMessage$GetActionStateRequest$Builder.build(MediationMessage.java:25192)
	at com.vmturbo.topology.processor.operation.OperationManager.getExternalActionState(OperationManager.java:1333)
	at com.vmturbo.topology.processor.actions.ActionApprovalService.requestExternalStateUpdates(ActionApprovalService.java:165)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

5. Using object method instead of public field of bean to fix:
`There is no live action store yet. Skipping action approval procedure` because `topologyContextId` was `0` when it should be `777777`.

6. Add EXTERNAL_APPROVAL to executable actions.
Could not accept approved action approval because mode was EXTERNAL_APPROVAL was not a valid mode of an executable action.

Known issues
============
1. the FAILED state did not reach ServiceNOW. this is a known issue to be addressed in https://vmturbo.atlassian.net/browse/OM59628

Unit Tests
==========
1. ActionApprovalManager can accept EXTERNAL_APPROVAL actions
2. All actions should have an explanation.

RB:39756