OM-46500: Reporting component - retry connections when repository/Arango is not available(RB31439)
Problem:

XL recently failed to generate report due to following exception in BoA environment, while trying to get cluster/members relationships from repository:

io.grpc.StatusRuntimeException: INTERNAL: java.util.concurrent.ExecutionException:
com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.

Investigation:

Currently report component doesn't have retry logic when connection failed.

Proposed fixes:

Add the retry logic for these exceptions.
Note: Currently, gRPC retry logic is not available (issues/284), but consider replace these changes when it's ready.

Other fixes: it's possible a VM in different group, and cause key violation exception when trying to add to default VM group (a group has all the VMs) again.

(cherry picked from commit 626f7c9)