[OM-65713]: RB-43173: Allow Empty List of Execution Schedule
Intent
======
Allow Empty List of Execution Schedule so that customers can upgrade from 7.22.5 to the latest without issues.

Problem
=======
When upgrading from 7.22.5 to 8.0.6 the following appears in the logs every 30 seconds:
```
2021-01-13 16:50:15,237 ERROR [default-settings-creator-0] [DefaultSettingPolicyCreator]	: Failed to create default policies
com.vmturbo.group.service.StoreOperationException: Invalid Policy Setting: Storage Defaults
Execution schedule setting `activateExecutionSchedule` should have only one schedule.
Execution schedule setting `resizeExecutionSchedule` should have only one schedule.
Execution schedule setting `provisionExecutionSchedule` should have only one schedule.
Execution schedule setting `deleteExecutionSchedule` should have only one schedule.
Execution schedule setting `suspendExecutionSchedule` should have only one schedule.
Execution schedule setting `moveExecutionSchedule` should have only one schedule.
	at com.vmturbo.group.setting.SettingStore.createSettingPolicies(SettingStore.java:214)
	at com.vmturbo.group.service.TransactionProviderImpl$SettingPolicyStoreImpl.createSettingPolicies(TransactionProviderImpl.java:164)
	at com.vmturbo.group.setting.DefaultSettingPolicyCreator.runIteration(DefaultSettingPolicyCreator.java:162)
	at com.vmturbo.group.setting.DefaultSettingPolicyCreator.lambda$runIteration$0(DefaultSettingPolicyCreator.java:102)
	at com.vmturbo.group.service.TransactionProviderImpl.lambda$transaction$0(TransactionProviderImpl.java:90)
	at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$0(DefaultDSLContext.java:536)
	at org.jooq.impl.Tools$12$1.block(Tools.java:4843)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
	at org.jooq.impl.Tools$12.get(Tools.java:4840)
	at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:588)
	at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:505)
	at com.vmturbo.group.service.TransactionProviderImpl.transaction(TransactionProviderImpl.java:79)
	at com.vmturbo.group.setting.DefaultSettingPolicyCreator.runIteration(DefaultSettingPolicyCreator.java:101)
	at com.vmturbo.group.setting.DefaultSettingPolicyCreator.run(DefaultSettingPolicyCreator.java:240)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Diagnosis
=========
Stack trace leads us to this check:
```
                final SortedSetOfOidSettingValue executionScheduleSettingValue =
                        scheduleSetting.getSortedSetOfOidSettingValue();
                if (executionScheduleSettingValue.getOidsCount() <= 1) {
                    schedulesUsed.addAll(executionScheduleSettingValue.getOidsList());
                } else {
                    errors.add("Execution schedule setting `" + scheduleSetting.getSettingSpecName()
                            + "` should have only one schedule.");
                }
```
In this case `executionScheduleSettingValue.getOidsCount()` is 0 which is also valid.

The reason we don't the this error in more recent builds is because more recent builds do not save the execution schedule in the initial, untouched default settings. In 7.22.5 we saved an empty execution schedule instead of no execution schedule for untouched default settings.

Solution
========
Change the condition from `executionScheduleSettingValue.getOidsCount() == 1` to `executionScheduleSettingValue.getOidsCount() <= 1` since no execution schedules are also valid.