[OM-67257]: voltron: load action orchestrator diags and voltron can disable system diags
Intent
=======
Load action orchestrator diags so AO related issues can be reproduced in voltron.
Flag to disable system diags since they don't work in voltron.

Problem
=======
1. Cannot load action orchestrator diags from bin/voltron.

2. Create diags from voltron takes 18+ minutes due to system diags:
```
2021-02-19 15:07:41,731 ERROR [qtp394424498-293] [BaseVmtComponent]	: Failed to collect system diagnostics. Will try to get component diagnostics.
com.vmturbo.components.common.diagnostics.DiagnosticsException: Error zipping temp diagnostic files onto diagnosticZip stream
...
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at com.vmturbo.components.common.diagnostics.DiagnosticService.getSystemDiags(DiagnosticService.java:83)
	at com.vmturbo.components.common.diagnostics.DiagnosticService.dumpSystemDiags(DiagnosticService.java:115)
	... 52 more
```

Dev test saving diags
======================
When no flag is set in MyWorkbench and you download diags you get the stacktrace in the problem section.

When `.globalPropertyOverride("enableSystemDiags", "false")` is set in MyWorkbench the diags are generated promptly with the following logs:
```
021-02-19 15:18:16,960  INFO [qtp394424498-472] [ClusterMgrService]	: applying REST REQUEST /diagnostics to component type: action-orchestrator [1 of 18]
2021-02-19 15:18:16,960  INFO [qtp394424498-472] [ClusterMgrService]	: - instance action-orchestrator-1 [1 of 1]
2021-02-19 15:18:16,964  INFO [qtp394424498-22] [DiagnosticsWriter]	: Creating zip entry serializedActions.diags with stream of strings
2021-02-19 15:18:16,964  INFO [qtp394424498-22] [DiagnosticsAppenderImpl]	: Creating zip entry serializedActions.diags with stream of strings
2021-02-19 15:18:16,982  INFO [qtp394424498-22] [DiagnosticsWriter]	: Creating zip entry workflow-identities.diags with stream of strings
2021-02-19 15:18:16,983  INFO [qtp394424498-22] [DiagnosticsAppenderImpl]	: Creating zip entry workflow-identities.diags with stream of strings
2021-02-19 15:18:16,994  INFO [qtp394424498-22] [DiagnosticsWriter]	: Creating zip entry workflows.diags with stream of strings
2021-02-19 15:18:16,994  INFO [qtp394424498-22] [DiagnosticsAppenderImpl]	: Creating zip entry workflows.diags with stream of strings
2021-02-19 15:18:17,013  INFO [qtp394424498-22] [WorkflowDiagnostics]	: Successfully exported 13 workflows to diagnostics
2021-02-19 15:18:17,014  INFO [qtp394424498-22] [DiagnosticsWriter]	: Creating zip entry PrometheusMetrics with stream of strings
2021-02-19 15:18:17,014  INFO [qtp394424498-22] [DiagnosticsAppenderImpl]	: Creating zip entry PrometheusMetrics with stream of strings
2021-02-19 15:18:17,014  INFO [qtp394424498-22] [PrometheusDiagnosticsProvider]	: Creating prometheus log entry PrometheusMetrics
2021-02-19 15:18:17,027  INFO [qtp394424498-22] [DiagnosticsWriter]	: Creating zip entry auditActions.diags with stream of strings
2021-02-19 15:18:17,027  INFO [qtp394424498-22] [DiagnosticsAppenderImpl]	: Creating zip entry auditActions.diags with stream of strings
2021-02-19 15:18:17,027  INFO [qtp394424498-472] [ClusterMgrService]	:  --- Begin diagnostic collection for action-orchestrator-1
2021-02-19 15:18:17,027  INFO [qtp394424498-472] [ClusterMgrService]	:  --- adding zip file named: action-orchestrator-1-diags.zip
2021-02-19 15:18:17,035  INFO [qtp394424498-22] [AuditActionsPersistenceDiagnostics]	: Successfully exported 0 auditedActions to diagnostics
2021-02-19 15:18:17,035  INFO [qtp394424498-472] [ClusterMgrService]	:  --- action-orchestrator-1 elapsed time: 0.075
2021-02-19 15:18:17,036  INFO [qtp394424498-472] [ClusterMgrService]	:  --- action-orchestrator-1 elapsed time: 0.076
2021-02-19 15:18:17,036  INFO [qtp394424498-472] [ClusterMgrService]	: applying REST REQUEST /diagnostics to component type: actionscript [2 of 18]
...
2021-02-19 15:18:17,965  INFO [qtp394424498-472] [ClusterMgrService]	:  --- topology-processor-1 elapsed time: 0.132
2021-02-19 15:18:17,965  INFO [qtp394424498-472] [ClusterMgrService]	:  --- topology-processor-1 elapsed time: 0.132
2021-02-19 15:18:17,965  INFO [qtp394424498-472] [ClusterMgrService]	: applying REST REQUEST /diagnostics to component type: vc [18 of 18]
2021-02-19 15:18:17,965  INFO [qtp394424498-472] [ClusterMgrService]	: - instance vc-1 [1 of 1]
2021-02-19 15:18:17,968  INFO [qtp394424498-281] [MediationComponentMain]	: Done collecting diags from vc-1
2021-02-19 15:18:17,968  INFO [qtp394424498-472] [ClusterMgrService]	:  --- Begin diagnostic collection for vc-1
2021-02-19 15:18:17,968  INFO [qtp394424498-472] [ClusterMgrService]	:  --- adding zip file named: vc-1-diags.zip
2021-02-19 15:18:17,968  INFO [qtp394424498-472] [ClusterMgrService]	:  --- vc-1 elapsed time: 0.003
2021-02-19 15:18:17,968  INFO [qtp394424498-472] [ClusterMgrService]	:  --- vc-1 elapsed time: 0.003
2021-02-19 15:18:17,968  INFO [qtp394424498-472] [ClusterMgrService]	:  - fetching rsyslog diagnostics
2021-02-19 15:18:17,971 ERROR [qtp394424498-472] [ClusterMgrService]	: Exception connecting to rsyslog. Diags will not have logs. Error: rsyslog: nodename nor servname provided, or not known
2021-02-19 15:18:17,971  INFO [qtp394424498-472] [ClusterMgrService]	:  - recording diagnostics environment summary
2021-02-19 15:18:17,977  INFO [qtp394424498-472] [ClusterMgrService]	:  - inserting diagnostics summary
2021-02-19 15:18:17,977  INFO [qtp394424498-472] [ClusterMgrService]	: finishing diagnosticZip
```

Dev test loading diags
======================
```
voltron restore_action_orchestrator action-orchestrator-1-diags.zip
Restoring from: /Users/josephmate/VMTurbo/scripts/xl_book_keeping_diags/journal/test/action-orchestrator-1-diags.zip
Successfully restored component state
2021-02-19 14:51:09,491  INFO [qtp775423528-282] [DiagnosticsHandlerImportable]	: Import from file workflow-identities.diags finished successfully
2021-02-19 14:51:09,492  INFO [qtp775423528-282] [DiagnosticsHandlerImportable]	: Importing string diagnostics from file workflows.diags
2021-02-19 14:51:09,493  INFO [qtp775423528-282] [WorkflowDiagnostics]	: Restoring 13 workflows from diags
2021-02-19 14:51:09,573  INFO [qtp775423528-282] [CachingIdentityStore]	: CachingIdentityStore loaded, items: 13
2021-02-19 14:51:09,577  INFO [qtp775423528-282] [PersistentWorkflowStore]	: 11 previous workflow items, 0 new workflow items
2021-02-19 14:51:09,625  INFO [qtp775423528-282] [PersistentWorkflowStore]	: 2 previous workflow items, 0 new workflow items
2021-02-19 14:51:09,640  INFO [qtp775423528-282] [WorkflowDiagnostics]	: Finished importing 13 workflows
2021-02-19 14:51:09,640  INFO [qtp775423528-282] [DiagnosticsHandlerImportable]	: Import from file workflows.diags finished successfully
2021-02-19 14:51:09,640  INFO [qtp775423528-282] [DiagnosticsHandlerImportable]	: Importing string diagnostics from file auditActions.diags
2021-02-19 14:51:09,641  INFO [qtp775423528-282] [AuditActionsPersistenceDiagnostics]	: Restoring 2 audited action book keeping from diags
2021-02-19 14:51:09,669  INFO [qtp775423528-282] [DiagnosticsHandlerImportable]	: Import from file auditActions.diags finished successfully
2021-02-19 14:51:09,669  INFO [qtp775423528-282] [DiagnosticsControllerImportable]	: Restoring component's state finished: Successfully restored component state
```

```
voltron restore_topology topology-processor-1-diags.zip
"Successfully restored 3 targets in 1 seconds"

...
2021-02-19 14:52:30,579  INFO [qtp775423528-20] [EntityStore]	: Restoring 426 entities for target 707171315633316
2021-02-19 14:52:30,584  INFO [qtp775423528-20] [TopologyProcessorDiagnosticsHandler]	: Done Restoring entities for target 707171315633316
2021-02-19 14:52:30,584  WARN [qtp775423528-20] [TopologyProcessorDiagnosticsHandler]	: Did not recognize diags file IncrementalEntities.707171315633316-1613762904846.diags
2021-02-19 14:52:30,585  INFO [qtp775423528-20] [TopologyProcessorDiagnosticsHandler]	: Restoring 17 discovered groups for target 707171315633316
2021-02-19 14:52:30,712  WARN [qtp775423528-20] [DiscoveredGroupInterpreter]	: Skipping group cdcd967d1e08d20936c3aa9a0879c635214c79ee as it is represented by entity already
2021-02-19 14:52:30,712  WARN [qtp775423528-20] [DiscoveredGroupInterpreter]	: Unable to parse group member list: member: "830f60de2e05ff291293eb5fe1e390968415bb82"
member: "fd944a49738b67d42b16e099468c952f21ddb969"
member: "59abc25eb23c7d85ef3014e82b774e3d660b7908"
member: "52666f0af81be7758ef9f2c8c7acb0fdbbd22e98"

2021-02-19 14:52:30,717  INFO [qtp775423528-20] [TopologyProcessorDiagnosticsHandler]	: Done restoring 17 discovered groups for target 707171315633316
2021-02-19 14:52:30,717  INFO [qtp775423528-20] [TopologyProcessorDiagnosticsHandler]	: Restoring 0 discovered setting policies for target 707171315633316
2021-02-19 14:52:30,717  INFO [qtp775423528-20] [TopologyProcessorDiagnosticsHandler]	: Done restoring 0 discovered setting policies for target 707171315633316
2021-02-19 14:52:30,717  INFO [qtp775423528-20] [TopologyProcessorDiagnosticsHandler]	: Restoring 9 discovered deployment profiles and associated templates for target 707171315633316
2021-02-19 14:52:30,781  INFO [qtp775423528-20] [TopologyProcessorDiagnosticsHandler]	: Done restoring 9 discovered deployment profiles and templates for target 707171315633316
2021-02-19 14:52:30,781  INFO [qtp775423528-20] [TopologyProcessorDiagnosticsHandler]	: 'PercentileEditor' state will be restored from 'Percentile.Editor.state.binary' file found in diagnostics.
2021-02-19 14:52:30,781  INFO [qtp775423528-20] [TopologyProcessorDiagnosticsHandler]	: 'TimeSlotEditor' state will be restored from 'Time.Slot.Editor.state.binary' file found in diagnostics.
2021-02-19 14:52:30,781  INFO [qtp775423528-20] [TopologyProcessorDiagnosticsHandler]	: Successfully restored 3 targets in 1 seconds
2021-02-19 14:52:30,781  INFO [qtp775423528-20] [TopologyProcessorDiagnosticsController]	: Restoring component's state finished: Successfully restored 3 targets in 1 seconds
```

```
voltron restore_groups group-1-diags.zip
Restoring from: /Users/josephmate/VMTurbo/scripts/xl_book_keeping_diags/journal/test/group-1-diags.zip
Successfully restored component stat

2021-02-19 14:53:50,824  INFO [qtp775423528-283] [DiagnosticsControllerImportable]	: Restoring component's state from diagnostics...
2021-02-19 14:53:50,825  INFO [qtp775423528-283] [TransactionalDiagnosticsHandlerImportable]	: Importing string diagnostics from file groups_dump.diags
2021-02-19 14:53:50,908  INFO [qtp775423528-283] [GroupDaoDiagnostics]	: Removed all the groups.
2021-02-19 14:53:50,909  INFO [qtp775423528-283] [GroupDaoDiagnostics]	: Attempting to restore 16 discovered groups and 1 non-discovered groups from diagnostics.
2021-02-19 14:53:51,059  INFO [qtp775423528-283] [GroupDaoDiagnostics]	: Restored 17 groups from diagnostics
2021-02-19 14:53:51,059  INFO [qtp775423528-283] [TransactionalDiagnosticsHandlerImportable]	: Import from file groups_dump.diags finished successfully
2021-02-19 14:53:51,059  INFO [qtp775423528-283] [TransactionalDiagnosticsHandlerImportable]	: Importing string diagnostics from file schedules_dump.diags
2021-02-19 14:53:51,059  INFO [qtp775423528-283] [ScheduleStore]	: Restoring schedules
2021-02-19 14:53:51,083  INFO [qtp775423528-283] [ScheduleStore]	: Imported 0 schedules
2021-02-19 14:53:51,083  INFO [qtp775423528-283] [TransactionalDiagnosticsHandlerImportable]	: Import from file schedules_dump.diags finished successfully
2021-02-19 14:53:51,083  INFO [qtp775423528-283] [TransactionalDiagnosticsHandlerImportable]	: Importing string diagnostics from file policies_dump.diags
2021-02-19 14:53:51,084  INFO [qtp775423528-283] [PolicyStore]	: Attempting to restore 0 policies from diagnostics.
2021-02-19 14:53:51,088  INFO [qtp775423528-283] [PolicyStore]	: Deleted 0 existing policies.
2021-02-19 14:53:51,088  INFO [qtp775423528-283] [PolicyStore]	: Finished restoring policies from diagnostics.
2021-02-19 14:53:51,088  INFO [qtp775423528-283] [TransactionalDiagnosticsHandlerImportable]	: Import from file policies_dump.diags finished successfully
2021-02-19 14:53:51,088  INFO [qtp775423528-283] [TransactionalDiagnosticsHandlerImportable]	: Importing string diagnostics from file settings_dump.diags
2021-02-19 14:53:51,095  INFO [qtp775423528-283] [SettingStore]	: Attempting to restore 55 global settings.
2021-02-19 14:53:51,162  INFO [qtp775423528-283] [SettingStore]	: Attempting to restore 22 setting policies.
2021-02-19 14:53:51,256  INFO [qtp775423528-283] [TransactionalDiagnosticsHandlerImportable]	: Import from file settings_dump.diags finished successfully
2021-02-19 14:53:51,256  INFO [qtp775423528-283] [TransactionalDiagnosticsHandlerImportable]	: Importing string diagnostics from file topology_data_definition_dump.diags
2021-02-19 14:53:51,263  INFO [qtp775423528-283] [TopologyDataDefinitionStore]	: All existing topology data definitions deleted.
2021-02-19 14:53:51,263  INFO [qtp775423528-283] [TopologyDataDefinitionStore]	: Attempting to parse 0 topology data definitions.
2021-02-19 14:53:51,264  INFO [qtp775423528-283] [TopologyDataDefinitionStore]	: Parsed 0 topology data definitions.
2021-02-19 14:53:51,264  INFO [qtp775423528-283] [TopologyDataDefinitionStore]	: Creating topology data defintions.
2021-02-19 14:53:51,264  INFO [qtp775423528-283] [TopologyDataDefinitionStore]	: 0 topology data definitions created. 0 errors encountered.
2021-02-19 14:53:51,264  INFO [qtp775423528-283] [TransactionalDiagnosticsHandlerImportable]	: Import from file topology_data_definition_dump.diags finished successfully
2021-02-19 14:53:51,265  INFO [qtp775423528-283] [TransactionalDiagnosticsHandlerImportable]	: Importing string diagnostics from file Topology.Data.Definitions.identifiers.diags
2021-02-19 14:53:51,268  INFO [qtp775423528-283] [TransactionalDiagnosticsHandlerImportable]	: Import from file Topology.Data.Definitions.identifiers.diags finished successfully
2021-02-19 14:53:51,274  INFO [qtp775423528-283] [DiagnosticsControllerImportable]	: Restoring component's state finished: Successfully restored component state
```

```
voltron restore_cost cost-1-diags.zip
Restoring from: /Users/josephmate/VMTurbo/scripts/xl_book_keeping_diags/journal/test/cost-1-diags.zip
Successfully restored component stat

...
2021-02-19 14:54:32,476  INFO [qtp775423528-17] [DiagnosticsHandlerImportable]	: Import from file latestReservedInstanceUtilization_dump.diags finished successfully
2021-02-19 14:54:32,476  INFO [qtp775423528-17] [DiagnosticsHandlerImportable]	: Importing string diagnostics from file planProjectedReservedInstanceUtilization_dump.diags
2021-02-19 14:54:32,476  INFO [qtp775423528-17] [DiagnosticsHandlerImportable]	: Import from file planProjectedReservedInstanceUtilization_dump.diags finished successfully
2021-02-19 14:54:32,476  INFO [qtp775423528-17] [DiagnosticsHandlerImportable]	: Importing string diagnostics from file planProjectedReservedInstanceCoverage_dump.diags
2021-02-19 14:54:32,476  INFO [qtp775423528-17] [DiagnosticsHandlerImportable]	: Import from file planProjectedReservedInstanceCoverage_dump.diags finished successfully
2021-02-19 14:54:32,476  INFO [qtp775423528-17] [DiagnosticsHandlerImportable]	: Importing string diagnostics from file planProjectedRIToEntity_dump.diags
2021-02-19 14:54:32,477  INFO [qtp775423528-17] [DiagnosticsHandlerImportable]	: Import from file planProjectedRIToEntity_dump.diags finished successfully
2021-02-19 14:54:32,477  INFO [qtp775423528-17] [DiagnosticsHandlerImportable]	: Importing string diagnostics from file EntityComputeTierAllocation_dump.diags
2021-02-19 14:54:32,477  INFO [qtp775423528-17] [DiagnosticsHandlerImportable]	: Import from file EntityComputeTierAllocation_dump.diags finished successfully
2021-02-19 14:54:32,477  INFO [qtp775423528-17] [DiagnosticsHandlerImportable]	: Importing string diagnostics from file sqlCloudScopeStore_dump.diags
2021-02-19 14:54:32,477  INFO [qtp775423528-17] [DiagnosticsHandlerImportable]	: Import from file sqlCloudScopeStore_dump.diags finished successfully
2021-02-19 14:54:32,477  INFO [qtp775423528-17] [DiagnosticsHandlerImportable]	: Importing string diagnostics from file computeTierDemand_dump.diags
2021-02-19 14:54:32,477  INFO [qtp775423528-17] [DiagnosticsHandlerImportable]	: Import from file computeTierDemand_dump.diags finished successfully
2021-02-19 14:54:32,477  INFO [qtp775423528-17] [DiagnosticsControllerImportable]	: Restoring component's state finished: Successfully restored component state
```